### ISSUE TITLE
Mattermost systemd service won't start on VPS with OpenVZ virtualisation

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/mattermost_ynh#100]
Hello,

During an upgrade the actual official repo version (the one without any restore script), it failed.
Mattermost service can't start.
Then I tried to remove it, and do a fresh install. Same result.
*Note: I used the official app repo, and the version is different from this master, but it doesn't work better with master.*

I have this error when trying to start the service : `mattermost.service: control process exited, code=exited status=124`

When checking the details with `journalctl -xn`, I have this message `failed to reset devices.list on /system.slice/mattermost.service`

Do you know what's going on ?

**Comment by kemenaran** [comment]
Oops, looks like something is wrong indeed – sorry for this ; I'll have a look by tomorrow.

Could you post which version of Debian and Yunohost you are running on this system?

**Comment by lapineige** [comment]
Debian Jessie and Yunohost 2.7.9.
Please ask me if you need more logs :)

**Comment by lapineige** [comment]
It's a bit off-topic, but btw I tried to restore the backup, but as this version had no restore script, I tried to add the restore script to the archive, but I have this error:

```
import csv
with open(sys.argv[1], '''r''') as backup_file:
    backup_csv = csv.DictReader(backup_file, fieldnames=['''source''', '''dest'''])
    for row in backup_csv:
        if row['''source''']==sys.argv[2].strip('''"'''):
        print row['''dest''']
    sys.exit(0)
raise Exception('''Original path for %s not found''' % sys.argv[2])
' /home/yunohost.backup/tmp/mattermost-pre-upgrade2/backup.csv '"/etc/nginx/conf.d/domain.tdl.d/mattermost.conf"'
Attention : Traceback (most recent call last):
Attention : File "<string>", line 10, in <module>
Attention : Exception: Original path for "/etc/nginx/conf.d/domain.tld.d/mattermost.conf" not found
```

**Comment by lapineige** [comment]
It's a bit off-topic, but btw I tried to restore the backup, but as this version had no restore script, I tried to add the restore script to the archive, but I have this error:

```
import csv
with open(sys.argv[1], '''r''') as backup_file:
    backup_csv = csv.DictReader(backup_file, fieldnames=['''source''', '''dest'''])
    for row in backup_csv:
        if row['''source''']==sys.argv[2].strip('''"'''):
        print row['''dest''']
    sys.exit(0)
raise Exception('''Original path for %s not found''' % sys.argv[2])
' /home/yunohost.backup/tmp/mattermost-pre-upgrade2/backup.csv '"/etc/nginx/conf.d/domain.tdl.d/mattermost.conf"'
Attention : Traceback (most recent call last):
Attention : File "<string>", line 10, in <module>
Attention : Exception: Original path for "/etc/nginx/conf.d/domain.tld.d/mattermost.conf" not found
```

And I don't understand this error, the backup.csv doesn't contain anything about this nginx conf file...

**Comment by kemenaran** [comment]
@lapineige So, the error message you got (`failed to reset devices.list`) seems to be a fairly common warning emitted by systemd when running inside an unprivileged LXC container.

Is your Yunohost setup using LXC containers at all? If not, this error message may be just a warning, and not the actual error; in this case could you paste the entire journalctl log somewhere?

**Comment by lapineige** [comment]
My VPS is running with OpenVZ virtualisation, but not LXC as far as I know.

I'm searching the log then I'll paste it :)

**Comment by lapineige** [comment]
The logs:

- installation log (I only pasted the part regarding systemd): https://vps.lapineige.fr/privatebin/?67a79d46a4e389c1#qUNYwnFjncmDh69pxjkYnjJeZJVbjfcP/IwAm70msBY=

- the details with journalctl -xn
> -- Subject: L'unité (unit) mattermost.service a commencé à démarrer
-- L'unité (unit) mattermost.service a commencé à démarrer.
:12 hostname systemd[1]: Failed to reset devices.list on /system.slice/mattermost.service: No such file or directory
:22 hostname systemd[1]: mattermost.service: control process exited, code=exited status=124
-- Subject: L'unité (unit) mattermost.service a échoué
-- L'unité (unit) mattermost.service a échoué, avec le résultat failed.
:22 hostname systemd[1]: Unit mattermost.service entered failed state.

All previous messages look normal, it's just the same as in the installation logs

**Comment by lapineige** [comment]
Do you know if there is a "more complete" way to remove Mattermost than the remove script ? (like an apt-get purge)

I'm wondering if it's not possible to remove any trace of the systemd service, where something seems broken.
I don't understand why removing everything including the service doesn't solve the issue.

**Comment by kemenaran** [comment]
I did some researches, and although the OpenVZ virtualization may cause these systemd warnings about "devices.list", they should not be fatal. Mattermost may be failing to start for another reason.

I'm trying to find some more logs. If you have still this broken version on your system, could you try to look for errors inside Mattermost own log files?

```shell
$ tail -f /var/log/mattermost/mattermost.log
# If the first command doesn't work:
$ tail -f /var/log/mattermost.log
```

Also, error messages may be printed to the console by starting the server directly, without using systemd:

```shell
$ sudo su mattermost
$ cd /var/www/mattermost
# Start the server
$ bin/platform server
```

Do you have any errors in this case?

> Do you know if there is a "more complete" way to remove Mattermost than the remove script ? (like an apt-get purge)

Well, not really – but to remove the systemd service, you can execute `sudo rm /etc/systemd/systemd/mattermost.service`. (The previous version of the package used `supervisor` as a process manager, and Yunohost may be attempting to use a previous version of the `remove` script as the upgrade failed, which would explain why the systemd service is not properly removed).

**Comment by lapineige** [comment]
No error when running it with `bin/platform server`
Just this log:
> Enterprise Enabled: true
Current working directory is /var/www/mattermost
Loaded config file from /var/www/mattermost/config/config.json
Loaded system translations for 'en' from '/var/www/mattermost/i18n/en.json'
Server is initializing...
Pinging SQL master database

But I can't check if it works, as installation fails (I use the `-n` option to keep the files), but it's not possible to connect to it using yunohost interface / url.

**Comment by lapineige** [comment]
>      

Well, not really – but to remove the systemd service, you can execute sudo rm /etc/systemd/systemd/mattermost.service. (The previous version of the package used supervisor as a process manager, and Yunohost may be attempting to use a previous version of the remove script as the upgrade failed, which would explain why the systemd service is not properly removed).

File doesn't exist.
It seems like the removal is complete.

**Comment by lapineige** [comment]
Btw I've setup a second instance, that I'll use instead, so there is no emergency.
But I can keep this instance for a few weeks, in case you want to investigate more.

**Comment by kemenaran** [comment]
Ok, thanks!

Does the second instance works properly on the same OpenVZ system? And which version of Mattermost is it running? I'm trying to see if the systemd config is hopelessly broken – or if it works when installed from scratch, but fails during an upgrade for some reason.

Also, which VPS provider and configuration are you using? I might try to reproduce the problem using the same service.

**Comment by lapineige** [comment]
> Does the second instance works properly on the same OpenVZ system?

Not it's a KVM system.
I installed Mattermost with `yunohost app install mattermost` (so the latest commit referenced in the community.json).
I did not upgrade this version as it is already up-do-date.

> Also, which VPS provider and configuration are you using? I might try to reproduce the problem using the same service.

It's not possible, the provider is PingFiles, but their recently changed their VPS offer, so it's no longer possible to  find the same config.

**Comment by kemenaran** [comment]
Closing for inactivity.
